export const DEFAULT_FILE_TYPES = ['js', 'jsx', 'ts', 'tsx', 'json'];
export const DEFAULT_IGNORE_SOURCES = ['node_modules', 'build', 'artifacts', 'engine_autogenerated', 'e2e', 'production-e2e', 'kompot', 'detox', 'coverage'];
export const DEFAULT_IGNORED_SOURCES_DESCRIPTION =
`1. Hidden files/folders
2. files includes 'config'
3. all files except package.json | index.t/js | app.t/js/x
4. folders includes 'demo'
5. ${DEFAULT_IGNORE_SOURCES.join(', ')})`;

/*** Mocks ***/

export const MOCKED_RAW_OPTIONS = {
  target: 'some_path',
  ignoredSources: DEFAULT_IGNORE_SOURCES.join('/')
}

export const MOCKED_PARSED_OPTIONS = {
  targetPath: 'some_path',
  ignoredSources: DEFAULT_IGNORE_SOURCES
}
